spring.application.name=PatientService
server.port=4000
#spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
#spring.datasource.username=admin
#spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=update

#H2 Database Configuration
spring.h2.console.path = /h2-console
spring.h2.console.enabled = true

spring.datasource.url=jdbc:h2:mem:patientpro
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
